name: Exectute detox for iOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.4

      - name: Install Dependencies
        run: yarn install

      - name: Installing applesimutils
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Installing Pods
        run: cd ios/ && pod install --repo-update && cd ..


      - name: Building App
        run: node node_modules/.bin/detox build --configuration ios

      - name: Testing App
        run: node node_modules/.bin/detox build --configuration ios --record-videos all --cleanup
